// src/utils/countryMapping.js
// Vollständiges Mapping: Country Name (DB) → GeoJSON ID

export const countryNameToGeoJsonId = {
  // Europa
  'Germany': 'DEU',
  'Italy': 'ITA',
  'France': 'FRA',
  'Spain': 'ESP',
  'Portugal': 'PRT',
  'Switzerland': 'CHE',
  'Austria': 'AUT',
  'Croatia': 'HRV',
  'Slovenia': 'SVN',
  'Greece': 'GRC',
  'Netherlands': 'NLD',
  'Belgium': 'BEL',
  'Poland': 'POL',
  'Czech Republic': 'CZE',
  'Denmark': 'DNK',
  'Sweden': 'SWE',
  'Norway': 'NOR',
  'Finland': 'FIN',
  'United Kingdom': 'GBR',
  'Ireland': 'IRL',
  'Iceland': 'ISL',
  'Estonia': 'EST',
  'Latvia': 'LVA',
  'Lithuania': 'LTU',
  'Slovakia': 'SVK',
  'Hungary': 'HUN',
  'Romania': 'ROU',
  'Bulgaria': 'BGR',
  'Serbia': 'SRB',
  'Bosnia and Herzegovina': 'BIH',
  'Montenegro': 'MNE',
  'Albania': 'ALB',
  'North Macedonia': 'MKD',
  'Luxembourg': 'LUX',
  'Monaco': 'MCO',
  'Liechtenstein': 'LIE',
  'Malta': 'MLT',
  'Cyprus': 'CYP',
  'Ukraine': 'UKR',
  'Belarus': 'BLR',
  'Moldova': 'MDA',
  'Russia': 'RUS',
  'Turkey': 'TUR',
  
  // Nord- & Südamerika
  'United States': 'USA',
  'United States of America': 'USA',
  'Canada': 'CAN',
  'Mexico': 'MEX',
  'Brazil': 'BRA',
  'Argentina': 'ARG',
  'Chile': 'CHL',
  'Peru': 'PER',
  'Colombia': 'COL',
  'Venezuela': 'VEN',
  'Ecuador': 'ECU',
  'Bolivia': 'BOL',
  'Paraguay': 'PRY',
  'Uruguay': 'URY',
  'Costa Rica': 'CRI',
  'Panama': 'PAN',
  'Cuba': 'CUB',
  'Jamaica': 'JAM',
  'Dominican Republic': 'DOM',
  
  // Asien
  'Japan': 'JPN',
  'China': 'CHN',
  'India': 'IND',
  'Thailand': 'THA',
  'Vietnam': 'VNM',
  'Indonesia': 'IDN',
  'Malaysia': 'MYS',
  'Singapore': 'SGP',
  'Philippines': 'PHL',
  'South Korea': 'KOR',
  'Taiwan': 'TWN',
  'Hong Kong': 'HKG',
  'Israel': 'ISR',
  'Jordan': 'JOR',
  'United Arab Emirates': 'ARE',
  'Saudi Arabia': 'SAU',
  'Qatar': 'QAT',
  'Nepal': 'NPL',
  'Sri Lanka': 'LKA',
  'Pakistan': 'PAK',
  'Bangladesh': 'BGD',
  'Myanmar': 'MMR',
  'Cambodia': 'KHM',
  'Laos': 'LAO',
  
  // Afrika
  'Egypt': 'EGY',
  'Morocco': 'MAR',
  'South Africa': 'ZAF',
  'Kenya': 'KEN',
  'Tanzania': 'TZA',
  'Ethiopia': 'ETH',
  'Nigeria': 'NGA',
  'Ghana': 'GHA',
  'Tunisia': 'TUN',
  'Algeria': 'DZA',
  'Namibia': 'NAM',
  'Botswana': 'BWA',
  'Zimbabwe': 'ZWE',
  'Uganda': 'UGA',
  'Rwanda': 'RWA',
  
  // Ozeanien
  'Australia': 'AUS',
  'New Zealand': 'NZL',
  'Fiji': 'FJI',
  'Papua New Guinea': 'PNG',
};
